import { DockerService } from "./types";

export const DEFAULT_SERVICES: DockerService[] = [
  {
    id: "immich",
    name: "Immich",
    port: 8484,
    iconName: "Image",
    description: "High performance self-hosted photo & video backup",
    category: "media",
    isActive: true,
  },
  {
    id: "seerr",
    name: "Seerr",
    port: 5055,
    iconName: "Sparkles",
    description: "Request management and media discovery tool",
    category: "media",
    isActive: true,
  },
  {
    id: "radarr",
    name: "Radarr",
    port: 7878,
    iconName: "Film",
    description: "Movie collection manager & automation tool",
    category: "media",
    isActive: true,
  },
  {
    id: "sonarr",
    name: "Sonarr",
    port: 8989,
    iconName: "Tv",
    description: "TV series collection manager & automation tool",
    category: "media",
    isActive: true,
  },
  {
    id: "plex",
    name: "Plex",
    port: 32400,
    iconName: "Flame",
    description: "Ultimate media streaming server for personal libraries",
    category: "media",
    isActive: true,
  },
  {
    id: "qbittorrent",
    name: "qBittorrent",
    port: 8080,
    iconName: "DownloadCloud",
    description: "BitTorrent client with secure VPN connection",
    category: "download",
    isActive: true,
  },
  {
    id: "audiobookshelf",
    name: "Audiobookshelf",
    port: 13378,
    iconName: "Headphones",
    description: "Self-hosted server for audiobooks and podcasts",
    category: "media",
    isActive: true,
  },
  {
    id: "lidarr",
    name: "Lidarr",
    port: 8686,
    iconName: "Music",
    description: "Music collection manager & automation tool",
    category: "media",
    isActive: true,
  },
  {
    id: "flaresolverr",
    name: "FlareSolverr",
    port: 8191,
    iconName: "Lock",
    description: "Cloudflare protection bypass proxy",
    category: "utility",
    isActive: true,
  },
  {
    id: "jackett",
    name: "Jackett",
    port: 9117,
    iconName: "Search",
    description: "API support for your favorite private trackers",
    category: "download",
    isActive: true,
  },
  {
    id: "nginx-proxy-manager",
    name: "Nginx Proxy Manager",
    port: 1880,
    iconName: "Globe",
    description: "Expose your docker containers securely with reverse proxy",
    category: "utility",
    isActive: true,
  },
  {
    id: "tautulli",
    name: "Tautulli",
    port: 8181,
    iconName: "Activity",
    description: "Monitoring and statistics for Plex Media Server",
    category: "utility",
    isActive: true,
  }
];
